name: Infostart
on:
  schedule: [{cron: "0 4 * * 1"}] # Расписание в Unix формате.
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest 
    permissions:
        contents: write
    steps:
      - uses: SerVer1C/metrics-infostart@v1.26
        with:
          user_id: '47774' # Infostart ID
          count: '10' # Количество выводимых статей. Сортировка по кол-ву звёзд.
          # template_file: '' # Путь к шаблону.
          # readme_file: '' # Путь к README файлу.
