name: Infostart
on:
  schedule: [{cron: "* * * * 0"}] # Расписание в Unix формате.
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest 
    permissions:
        contents: write
    steps:
      - run: ls -la
      - uses: SerVer1C/metrics-infostart@v1.10
        with:
          user_id: '47774' # Infostart ID
          count: '7' # Количество выводимых статей. Сортировка по кол-ву звёзд.
          template_file: './template.html' # Путь к шаблону.
          readme_file: './README.md' # Путь к README файлу.
 
